const sessionManager = require('./sessionManager');

const VISUALIZATIONS = {
    'bubble': {
        name: "Bubble Sort (C)",
        file: 'bubble.c',
        code: [
            '#include <stdio.h>',
            '#include <stdlib.h>',
            '#include <unistd.h>',
            '#include <time.h>',
            '',
            '#define SIZE 10',
            '#define DELAY 150000',
            '',
            'void print_array(int arr[], int size, int active1, int active2) {',
            '    puts("Visualizing Bubble Sort (C)");',
            '    puts("---------------------------");',
            '    for (int i = 0; i < size; i++) {',
            '        for (int j = 0; j < arr[i]; j++) printf("#");',
            '        printf(" (%d)", arr[i]);',
            '        if (i == active1 || i == active2) printf(" <--");',
            '        puts("");',
            '    }',
            '    puts("");',
            '    fflush(stdout);',
            '}',
            '',
            'int main() {',
            '    int arr[SIZE] = {9, 3, 5, 1, 8, 2, 7, 4, 10, 6};',
            '    for (int i = 0; i < SIZE - 1; i++) {',
            '        for (int j = 0; j < SIZE - i - 1; j++) {',
            '            print_array(arr, SIZE, j, j + 1);',
            '            usleep(DELAY);',
            '            if (arr[j] > arr[j + 1]) {',
            '                int temp = arr[j];',
            '                arr[j] = arr[j + 1];',
            '                arr[j + 1] = temp;',
            '                print_array(arr, SIZE, j, j + 1);',
            '                usleep(DELAY);',
            '            }',
            '        }',
            '    }',
            '    print_array(arr, SIZE, -1, -1);',
            '    puts("Sorted!");',
            '    return 0;',
            '}'
        ].join('\n')
    },
    'selection': {
        name: "Selection Sort (C)",
        file: 'selection.c',
        code: [
            '#include <stdio.h>',
            '#include <stdlib.h>',
            '#include <unistd.h>',
            '',
            '#define SIZE 10',
            '#define DELAY 200000',
            '',
            'void print_array(int arr[], int size, int min_idx, int current) {',
            '    puts("Visualizing Selection Sort (C)");',
            '    puts("------------------------------");',
            '    for (int i = 0; i < size; i++) {',
            '        for (int j = 0; j < arr[i]; j++) printf("#");',
            '        printf(" (%d)", arr[i]);',
            '        if (i == min_idx) printf(" <-- [MIN]");',
            '        else if (i == current) printf(" <-- [SCAN]");',
            '        puts("");',
            '    }',
            '    puts("");',
            '    fflush(stdout);',
            '}',
            '',
            'int main() {',
            '    int arr[SIZE] = {7, 2, 9, 1, 5, 10, 4, 3, 8, 6};',
            '    for (int i = 0; i < SIZE - 1; i++) {',
            '        int min_idx = i;',
            '        for (int j = i + 1; j < SIZE; j++) {',
            '            print_array(arr, SIZE, min_idx, j);',
            '            usleep(DELAY);',
            '            if (arr[j] < arr[min_idx]) min_idx = j;',
            '        }',
            '        int temp = arr[min_idx];',
            '        arr[min_idx] = arr[i];',
            '        arr[i] = temp;',
            '    }',
            '    print_array(arr, SIZE, -1, -1);',
            '    puts("Sorted!");',
            '    return 0;',
            '}'
        ].join('\n')
    },
    'quick': {
        name: "Quick Sort (C)",
        file: 'quick.c',
        code: [
            '#include <stdio.h>',
            '#include <stdlib.h>',
            '#include <unistd.h>',
            '',
            '#define SIZE 10',
            '#define DELAY 250000',
            '',
            'void print_array(int arr[], int size, int p, int low, int high) {',
            '    puts("Visualizing Quick Sort (C)");',
            '    puts("--------------------------");',
            '    for (int i = 0; i < size; i++) {',
            '        for (int j = 0; j < arr[i]; j++) printf("#");',
            '        printf(" (%d)", arr[i]);',
            '        if (i == p) printf(" <-- [PIVOT]");',
            '        else if (i >= low && i <= high) printf(" <--");',
            '        puts("");',
            '    }',
            '    puts("");',
            '    fflush(stdout);',
            '}',
            '',
            'int partition(int arr[], int low, int high, int size) {',
            '    int pivot = arr[high];',
            '    int i = (low - 1);',
            '    for (int j = low; j <= high - 1; j++) {',
            '        print_array(arr, size, high, i+1, j);',
            '        usleep(DELAY);',
            '        if (arr[j] < pivot) {',
            '            i++;',
            '            int t = arr[i]; arr[i] = arr[j]; arr[j] = t;',
            '        }',
            '    }',
            '    int t = arr[i + 1]; arr[i + 1] = arr[high]; arr[high] = t;',
            '    return (i + 1);',
            '}',
            '',
            'void quickSort(int arr[], int low, int high, int size) {',
            '    if (low < high) {',
            '        int pi = partition(arr, low, high, size);',
            '        quickSort(arr, low, pi - 1, size);',
            '        quickSort(arr, pi + 1, high, size);',
            '    }',
            '}',
            '',
            'int main() {',
            '    int arr[SIZE] = {10, 7, 8, 9, 1, 5, 2, 4, 3, 6};',
            '    quickSort(arr, 0, SIZE - 1, SIZE);',
            '    print_array(arr, SIZE, -1, -1, -1);',
            '    puts("Sorted!");',
            '    return 0;',
            '}'
        ].join('\n')
    }
};

class VisualizationManager {
    async prepareVisualization(sessionId, vizId) {
        const viz = VISUALIZATIONS[vizId];
        if (!viz) throw new Error("Visualization not found.");
        const b64 = Buffer.from(viz.code).toString('base64');
        await sessionManager.executeCommand(sessionId, `echo "${b64}" | base64 -d > ${viz.file}`);
        const compileCmd = `gcc ${viz.file} -o ${vizId}_app`;
        const result = await sessionManager.executeCommand(sessionId, compileCmd);
        if (result.error) throw new Error(`Compilation failed: ${result.error}`);
        return `./${vizId}_app`;
    }
}

module.exports = new VisualizationManager();